name: 'Cool Bikes at Liberty! Bicycles'
favicon: null
layout_spectrum: 0.92547
typography_spectrum: 0.49061
title: 'Cool Bikes at Liberty! Bicycles'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefcff'
    - '#6b6764'
    - '#000000'
    - '#323f47'
    - '#c5c0bc'
  brandStrength: 0.8783156764693558
  lightness: 0.6875
  saturation: 0.45892018754966557
  rhythmicContrast: 0.7809897414408624
purpose: []
